"""
Buddyliko Procedure Retriever
─────────────────────────────
Deterministic keyword/trigger matching against procedures_index.json.
Used by /api/ai/chat to inject relevant procedure docs into the LLM context.

Supports:
- .md/.html procedure documents
- Screenshot images (base64 injection ready)
- Audio/video transcripts (auto-generated by external tool)
"""
import json, re, os, glob
from dataclasses import dataclass, asdict, field
from typing import List, Dict, Optional

PROC_BASE = os.path.join(os.path.dirname(__file__), "procedures")
INDEX_PATH = os.path.join(PROC_BASE, "config", "procedures_index.json")
ASSETS_DIR = os.path.join(PROC_BASE, "assets")
TRANSCRIPTS_DIR = os.path.join(ASSETS_DIR, "transcripts")

# ── Lazy-loaded index ──
_index_cache: Optional[Dict] = None
_transcript_cache: Optional[Dict] = None  # filename_stem -> transcript text

def _load_index() -> Dict:
    global _index_cache
    if _index_cache is None:
        with open(INDEX_PATH, "r", encoding="utf-8") as f:
            _index_cache = json.load(f)
    return _index_cache

def _load_transcripts() -> Dict[str, str]:
    """Load all transcripts from assets/transcripts/ into memory."""
    global _transcript_cache
    if _transcript_cache is None:
        _transcript_cache = {}
        if os.path.isdir(TRANSCRIPTS_DIR):
            for fpath in glob.glob(os.path.join(TRANSCRIPTS_DIR, "*.md")):
                stem = os.path.basename(fpath)  # e.g. PROC-0300-tutorial.mp4.transcript.md
                try:
                    with open(fpath, "r", encoding="utf-8") as f:
                        _transcript_cache[stem] = f.read()
                except Exception:
                    pass
    return _transcript_cache

def reload_index():
    """Force reload (call after adding new procedures or transcripts)."""
    global _index_cache, _transcript_cache
    _index_cache = None
    _transcript_cache = None
    return _load_index()


@dataclass
class MediaAsset:
    type: str          # "screenshot" | "audio" | "video"
    filename: str      # file in assets/{type}/
    transcript: str = ""  # transcript content if available
    url: str = ""      # served URL (for frontend links)

    def to_dict(self):
        return asdict(self)


@dataclass
class RetrievedProcedure:
    id: str
    title: str
    path: str
    score: float
    source: str  # v1_howto | v2_api
    content: str = ""
    media: List[MediaAsset] = field(default_factory=list)

    def to_dict(self):
        d = asdict(self)
        d.pop("content", None)
        return d


def _normalize(s: str) -> str:
    s = s.lower()
    s = re.sub(r"[^a-z0-9àèéìòùçäöüß_/-]+", " ", s)
    return s.strip()

def _tokenize(text: str) -> List[str]:
    return [t for t in _normalize(text).split() if len(t) > 1]


def _score_proc(query_norm: str, query_tokens: set, proc: Dict) -> float:
    score = 0.0

    # Keywords (2 pts each match)
    kw = set(_normalize(k) for k in proc.get("keywords", []))
    score += 2.0 * len(query_tokens & kw)

    # Trigger phrases (6 pts if found in query)
    for trigger in proc.get("triggers", []):
        t = _normalize(trigger)
        if t and t in query_norm:
            score += 6.0

    # API endpoint mention (5 pts)
    for ep in proc.get("api_endpoints", []):
        if _normalize(ep) in query_norm:
            score += 5.0

    # UI page mention (4 pts)
    for pg in proc.get("ui_pages", []):
        pg_n = _normalize(pg)
        if pg_n in query_norm:
            score += 4.0

    # Category match on common terms
    cat = _normalize(proc.get("category", ""))
    cat_terms = {
        "auth": {"login", "registr", "password", "mfa", "accedi", "accesso", "autenticazione"},
        "mapper": {"mapping", "mappa", "mappatura", "trasform", "transform", "convert", "drag", "drop", "formula"},
        "workspace": {"file", "upload", "download", "cartella", "folder", "progetto", "project", "workspace"},
        "schemas": {"schema", "xsd", "csv", "json", "xml", "edi", "hl7", "idoc", "fhir", "parse"},
        "validation": {"validat", "validaz", "xsd", "schematron"},
        "db": {"database", "db", "postgres", "mysql", "sql", "connector", "connettore", "tabella", "table"},
        "batch": {"batch", "parallelo", "parallel", "zip", "massa"},
        "scheduling": {"schedule", "schedul", "cron", "pianific", "ricorrente", "recurring"},
        "webhooks": {"webhook", "hook", "evento", "event", "notifica", "notification", "hmac"},
        "org": {"organizzazione", "organization", "utenti", "users", "ruolo", "role", "membro", "member", "team"},
        "billing": {"billing", "fatturazione", "piano", "plan", "abbonamento", "subscription", "stripe", "budget", "costo", "cost"},
        "marketplace": {"marketplace", "template", "acquist", "purchase", "pubblica", "publish", "clona", "clone"},
        "standards": {"standard", "fatturapa", "ubl", "peppol", "edifact", "x12", "hl7", "fhir"},
        "admin": {"admin", "amministr", "audit", "log"},
        "finance": {"finance", "finanz", "mrr", "profittab", "profitab", "revenue", "pricing", "alert"},
        "ai": {"ai", "automap", "auto-map", "intelligenz", "artificial"},
        "troubleshooting": {"errore", "error", "problema", "problem", "debug", "troubleshoot", "non funziona", "doesn't work", "broken", "rotto"},
    }
    if cat in cat_terms:
        matches = sum(1 for t in query_tokens if any(t.startswith(stem) or stem in t for stem in cat_terms[cat]))
        score += 1.5 * matches

    # Bonus: V1 how-to procedures get a boost (they're more detailed/useful)
    if proc.get("source") == "v1_howto" and score > 0:
        score *= 1.5

    return score


def _find_media_for_proc(proc_id: str) -> List[MediaAsset]:
    """Find screenshots, audio, video files associated with a procedure ID."""
    media = []
    transcripts = _load_transcripts()
    
    for media_type in ("screenshots", "audio", "video"):
        media_dir = os.path.join(ASSETS_DIR, media_type)
        if not os.path.isdir(media_dir):
            continue
        for fpath in os.listdir(media_dir):
            if fpath.startswith(proc_id) and not fpath.endswith("README.md"):
                asset = MediaAsset(
                    type=media_type.rstrip("s"),  # screenshots -> screenshot
                    filename=fpath,
                    url=f"/procedures/assets/{media_type}/{fpath}",
                )
                # Check for transcript
                transcript_name = f"{fpath}.transcript.md"
                if transcript_name in transcripts:
                    asset.transcript = transcripts[transcript_name]
                media.append(asset)
    return media


def _search_transcripts(query_norm: str, query_tokens: set) -> List[RetrievedProcedure]:
    """Search through transcript files for matching content."""
    transcripts = _load_transcripts()
    results = []
    for fname, content in transcripts.items():
        content_norm = _normalize(content[:2000])  # First 2000 chars
        score = 0.0
        for token in query_tokens:
            if token in content_norm:
                score += 1.0
        if score >= 2.0:
            # Extract PROC-ID from filename if possible
            proc_match = re.search(r"(PROC-\d+)", fname)
            proc_id = proc_match.group(1) if proc_match else fname
            results.append(RetrievedProcedure(
                id=proc_id,
                title=f"Transcript: {fname}",
                path=f"assets/transcripts/{fname}",
                score=score,
                source="transcript",
                content=content,
            ))
    return results


def retrieve(query: str, top_k: int = 5, include_content: bool = False) -> List[RetrievedProcedure]:
    """
    Find the most relevant procedures for a query.
    
    Args:
        query: User question (any language)
        top_k: Max results
        include_content: If True, read and attach the full .md/.html content
    
    Returns:
        List of RetrievedProcedure sorted by relevance
    """
    index = _load_index()
    qn = _normalize(query)
    qt = set(_tokenize(query))

    results: List[RetrievedProcedure] = []
    for proc in index["procedures"]:
        score = _score_proc(qn, qt, proc)
        if score > 0:
            results.append(RetrievedProcedure(
                id=proc["id"],
                title=proc["title"],
                path=proc["path"],
                score=score,
                source=proc.get("source", "unknown"),
            ))

    # Also search transcripts
    transcript_results = _search_transcripts(qn, qt)
    # Merge: if a transcript matches a proc already found, boost its score
    existing_ids = {r.id for r in results}
    for tr in transcript_results:
        if tr.id in existing_ids:
            for r in results:
                if r.id == tr.id:
                    r.score += tr.score  # Boost
                    break
        else:
            results.append(tr)

    results.sort(key=lambda x: x.score, reverse=True)
    results = results[:top_k]

    if include_content:
        for r in results:
            if r.source == "transcript" and r.content:
                continue  # Already has content
            filepath = os.path.join(PROC_BASE, r.path)
            try:
                with open(filepath, "r", encoding="utf-8") as f:
                    r.content = f.read()
            except FileNotFoundError:
                r.content = f"[Procedure file not found: {r.path}]"
            
            # Attach media assets
            r.media = _find_media_for_proc(r.id)
            
            # Append transcript content if media has transcripts
            for m in r.media:
                if m.transcript:
                    r.content += f"\n\n### 🎬 Transcript ({m.filename})\n{m.transcript}"

    return results


def list_categories() -> List[str]:
    """Return all unique categories."""
    index = _load_index()
    return sorted(set(p.get("category", "MISC") for p in index["procedures"]))


def list_procedures(category: str = None) -> List[Dict]:
    """List all procedures, optionally filtered by category."""
    index = _load_index()
    procs = index["procedures"]
    if category:
        procs = [p for p in procs if p.get("category", "").upper() == category.upper()]
    return [{"id": p["id"], "title": p["title"], "category": p.get("category", "MISC")} for p in procs]


def get_procedure_content(proc_id: str) -> Optional[str]:
    """Read a single procedure by ID."""
    index = _load_index()
    for p in index["procedures"]:
        if p["id"] == proc_id:
            filepath = os.path.join(PROC_BASE, p["path"])
            try:
                with open(filepath, "r", encoding="utf-8") as f:
                    return f.read()
            except FileNotFoundError:
                return None
    return None


# ── CLI test ──
if __name__ == "__main__":
    import sys
    q = " ".join(sys.argv[1:]) or "Come creo un mapping FatturaPA?"
    print(f"Query: {q}\n")
    for r in retrieve(q, top_k=5, include_content=False):
        print(f"  [{r.score:.1f}] {r.id} — {r.title} ({r.source})")
